### ISSUE TITLE
yeti::scenario_pack Opcode not recognized

### ISSUE THREAD

**Issue by AmarenaCherry** [WarpspeedSCP/yet-cc-rs#2]
After compilation, I tried decompiling sn.bin from my copy of and encountered this error:

> [ERROR yeti::scenario_pack] Encountered an error (Opcode FF not recognised at address 0x0000000C.) while decoding entry at offset 0x0056EB50 of size 0x00001620

Using the sn.bin in the README link, I encounter similar errors:

> [ERROR yeti::scenario_pack] Encountered an error (Opcode 77 not recognised at address 0x000006B6.) while decoding entry at offset 0x001CEF87 of size 0x00006B0E
> [ERROR yeti::scenario_pack] Encountered an error (Opcode FF not recognised at address 0x0000000C.) while decoding entry at offset 0x00570055 of size 0x00001620

**Comment by WarpspeedSCP** [comment]
Oh, the first one isn't actualyl fatal. you can verify that by running `yeti recomp` with the output directory you specified earlier as input, and feeding that back to the game, it'll work fine. I'll push a change that makes that more of an info message than an error.

the second output you've shared is unfortunately one of the current limitations of this tool; you can't unpack scenarios with the tip opcode because of how that opcode works.

**Comment by WarpspeedSCP** [comment]
@AmarenaCherry this should be fixed now; you should even be able to decode the modified sn.bin I shared. Pull and recompile, and it should work.

**Comment by WarpspeedSCP** [comment]
@AmarenaCherry btw, I'd love to help if you're working on a translation of CC. I've barely just started on my effort, and only really got as far as creating this tool. Please do let me know if you're open to that.

**Comment by AmarenaCherry** [comment]
@WarpspeedSCP My only interest was searching for tools for yeti/regista, I'm not exactly interested in a CC translation. I do know someone who [is looking for people though](https://forums.fuwanovel.moe/topic/32134-cross-channel-translation-need-editor-hacker-second-translator/#comment-548401), you can always try and contact them (they're a friend of mine).
